### ISSUE TITLE
Editing course results in app crash

### ISSUE THREAD

**Issue by nickthegroot** [nickthegroot/UnityPlanner#28]
```
Caused by: java.lang.IllegalArgumentException: DTEND and DURATION cannot both be null for an event.
                                                                at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
                                                                at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
                                                                at android.content.ContentResolver.insert(ContentResolver.java:1539)
                                                                at com.nbdeg.unityplanner.EditCourse$EditCalEvent.doInBackground(EditCourse.java:353)
                                                                at com.nbdeg.unityplanner.EditCourse$EditCalEvent.doInBackground(EditCourse.java:295)
```

**Comment by nickthegroot** [comment]
Fixed in commit 600eb70a94942b43cf1a9d88d05f08428bea99c8. Will be live in v1.1 release.
